### PR TITLE
Add support for a subcommand

### PR DESCRIPTION
**Pull request by andymac4182**
This is designed to allow for the first proposal in https://github.com/datalust/seqcli/issues/2.

I am building a proposal for API Key management which is where this came from.

```
seqcli apikey list
seqcli apikey get -n="ApplicationName"
```

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks for the PR! Looks great :+1: will check it out in the morning with fresh eyes :-)

**Comment by andymac4182** [comment]
From my perspective this is good to go now. There should be tests for the new logic and ensuring I didn't break old logic.

**Comment by nblumhardt** [comment]
I think we'll need to add some more tweaks to get:

```
seqcli help
```

and

```
seqcli help apikey
```

working with it, but seems like a good time to push this through to unblock #27 :-)

Thanks again!

**Comment by andymac4182** [comment]
I will have a look at help to see if I can get that working.

**Pull request merged**
