### PR TITLE
Add extra commands for Settings, License, Truncate, Retention Policy and extra options to Ingest and Create

### PR DESCRIPTION
**Pull request by andymac4182**
This is adding the ability to find and update settings. 

Value is currently an `Object` in the `Seq.Api` project. Are there particular types that need to be handled or is it just int or string?

I am doing this so I can mainly update the authentication settings in an automated manner.

### CODE REVIEW

**Comment by andymac4182** [comment]
Is it possible to get a single user license that I could use for the EndToEnd test of adding a license or if there is a test license I can load in to test it going in and out.

**Comment by nblumhardt** [comment]
I think numbers and strings are the only things we'll commonly see in `Value`; it's a bit hazy, though - will need to look into it.

I'll have a look at options for testing license manipulation, thanks for checking this out :)

**Comment by nblumhardt** [comment]
Howdy @andymac4182! Hope all is going well in your neck of the woods :-)

Still working on this PR? Another possible way forward might be to close it, and submit each of the different bits and pieces in smaller individual PRs?

No rush at all, just checking in 👍

**Comment by nblumhardt** [comment]
Closing this as stale, but sing out if you want to reopen :-)

**Pull request closed without merging**
