### PR TITLE
Added create, remove and list commands for workspaces

### PR DESCRIPTION
**Pull request by andreas-nesheim**
As referenced in [Issue 130](https://github.com/datalust/seqcli/issues/130). Added a new CLI command for workspace. These commands include:

- create
- list
- remove

Hope you find this useful. I'd be willing to have a go at implementing commands for adding and removing signals to the workspace as well if this PR looks good.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thank you @andreas-nesheim - looks great.

We can definitely fill in the "modify" part; I was wondering, though, should we look at supporting this on `create` as:

```
seqcli workspace create -t 'test' --signal=signal-123 --signal=signal-124 --dashboard=dashboard-456
```

Keen to hear opinions :-)

**Comment by andreas-nesheim** [comment]
Sure, that sounds like a good idea! I'll try to implement it.

**Comment by andreas-nesheim** [comment]
I tried to add the options that we discussed now, but I see one of the tests in Appveyor is failing. When I try to run it locally it works, though.

**Comment by nblumhardt** [comment]
Thanks! I think the CI failure is a timing issue we haven't managed to flush out; it'd be unrelated to this PR. I've queued the build back up, everything looks good, we can tinker from here :-) 👍

**Pull request merged**
