### PR TITLE
Allow updating signals

### PR DESCRIPTION
**Pull request by AlbertoSadoc**
When importing signals if a signal with the same id is found it will update the values instead of inserting a new one.

Related to #145

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks for the PR! This would be a great addition.

Since `signal import` effectively ignores the `Id`s of source signals, this could cause some surprising changes in behavior for existing users of the command. Perhaps the new behavior could be enabled through a new flag, such as `--merge`?

**Comment by AlbertoSadoc** [comment]
Yes, that is a great point. I will amend that

**Comment by AlbertoSadoc** [comment]
@nblumhardt `--merge` option added suggested.

**Comment by nblumhardt** [comment]
Thank you; looks good, I'll need a few spare minutes to review, but think this is the way to go 👍

**Comment by nblumhardt** [comment]
Thanks again! Sorry about the delay; this will make it into the 2020.3 release.

**Comment by danielloczi** [comment]
Hi. I'm facing an issue, which relates to this ticket. The id defined in the imported signal is ignored, and the new signal is getting a different id. Please check this ticket: https://github.com/datalust/seq-tickets/issues/1718

**Pull request merged**
